global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: /metrics

  - job_name: "solr-master"
    static_configs:
      - targets: ["solr-master:9983"]

  - job_name: "solr-slave1"
    static_configs:
      - targets: ["solr-slave1:9983"]

  - job_name: "solr-slave2"
    static_configs:
      - targets: ["solr-slave2:9983"]
