global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]


  - job_name: "solr-exporters"
    static_configs:
      - targets:
        - "solr-master-exporter:9983"
        - "solr-slave1-exporter:9983"
        - "solr-slave2-exporter:9983"
